version: 0.2

env:
  variables:
    AWS_REGION: "us-west-2"
    JAVA_REPO_URI: "497588665354.dkr.ecr.us-east-1.amazonaws.com/ecomm/java-inventory-service"
    PYTHON_REPO_URI: "497588665354.dkr.ecr.us-east-1.amazonaws.com/ecomm/pricing-service"
    IMAGE_TAG: "latest"
    TRIVY_VERSION: "0.51.0"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - echo Installing Trivy...
      - wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
      - tar -xzf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin
      - rm trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
      - trivy image --download-db-only

  build:
    commands:
      - echo Build started on `date`

      - echo Building the Java Inventory Service Docker image...
      - docker build -t $JAVA_REPO_URI:$IMAGE_TAG -f java-inventory-service/Dockerfile java-inventory-service/.
      - docker tag $JAVA_REPO_URI:$IMAGE_TAG $JAVA_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo Building the Python Pricing Service Docker image...
      - docker build -t $PYTHON_REPO_URI:$IMAGE_TAG -f pricing-service/Dockerfile pricing-service/.
      - docker tag $PYTHON_REPO_URI:$IMAGE_TAG $PYTHON_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo "--- Scanning Java Inventory Service Image ---"
      - trivy image --exit-code 1 --severity CRITICAL $JAVA_REPO_URI:$IMAGE_TAG

      - echo "--- Scanning Python Pricing Service Image ---"
      - trivy image --exit-code 1 --severity CRITICAL $PYTHON_REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Security scans passed. Build completed successfully on `date`

      - echo Pushing the Java Inventory Service Docker image...
      - docker push $JAVA_REPO_URI:$IMAGE_TAG
      - docker push $JAVA_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo Pushing the Python Pricing Service Docker image...
      - docker push $PYTHON_REPO_URI:$IMAGE_TAG
      - docker push $PYTHON_REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

      - echo Writing image definitions and K8s manifests for deployment artifact.
      - printf '[{"name":"java-inventory-service","imageUri":"%s"}, {"name":"pricing-service","imageUri":"%s"}, {"name":"pricing-consumer-canary","imageUri":"%s"}]' $JAVA_REPO_URI:$IMAGE_TAG $PYTHON_REPO_URI:$IMAGE_TAG $PYTHON_REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - 'k8s/configmap.yaml'
    - 'k8s/java-inventory-deployment.yaml'
    - 'k8s/pricing-deployment.yaml'
    - 'k8s/pricing-deployment-canary.yaml'
    - 'imagedefinitions.json'